import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from '@google/genai';
import { Sparkles, Loader2, Key } from 'lucide-react';

interface AIGeneratedImageProps {
  prompt: string;
  defaultSrc: string;
  alt: string;
  className?: string;
}

export default function AIGeneratedImage({ prompt, defaultSrc, alt, className }: AIGeneratedImageProps) {
  const [imageUrl, setImageUrl] = useState<string>(defaultSrc);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasKey, setHasKey] = useState(false);

  useEffect(() => {
    const checkKey = async () => {
      try {
        // @ts-ignore
        if (window.aistudio && await window.aistudio.hasSelectedApiKey()) {
          setHasKey(true);
        }
      } catch (e) {
        console.error("Error checking API key:", e);
      }
    };
    checkKey();
  }, []);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);

    try {
      // @ts-ignore
      if (window.aistudio && !(await window.aistudio.hasSelectedApiKey())) {
        // @ts-ignore
        await window.aistudio.openSelectKey();
        setHasKey(true);
      }

      // The selected API key is available using process.env.API_KEY
      const apiKey = process.env.API_KEY;
      if (!apiKey) {
        throw new Error("API key not found after selection.");
      }

      const ai = new GoogleGenAI({ apiKey });
      
      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image-preview',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9",
            imageSize: "1K"
          }
        }
      });

      let foundImage = false;
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          const base64EncodeString = part.inlineData.data;
          setImageUrl(`data:image/png;base64,${base64EncodeString}`);
          foundImage = true;
          break;
        }
      }

      if (!foundImage) {
        throw new Error("No image generated by the model.");
      }

    } catch (err: any) {
      console.error("Image generation error:", err);
      
      const errorMessage = typeof err === 'object' ? (err.message || JSON.stringify(err)) : String(err);
      
      // If entity not found or permission denied (e.g., free tier key used for paid model)
      if (
        errorMessage.includes("Requested entity was not found") || 
        errorMessage.includes("PERMISSION_DENIED") || 
        errorMessage.includes("403") ||
        errorMessage.includes("caller does not have permission")
      ) {
        setError("Permission denied. Please ensure you select an API key from a paid Google Cloud project with billing enabled.");
        setHasKey(false);
        // @ts-ignore
        if (window.aistudio) window.aistudio.openSelectKey();
      } else {
        setError(errorMessage || "Failed to generate image");
      }
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="relative group w-full h-full">
      <img
        src={imageUrl}
        alt={alt}
        className={className}
        draggable={false}
        referrerPolicy="no-referrer"
      />
      
      <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity bg-black/40 backdrop-blur-sm rounded-2xl">
        {isGenerating ? (
          <div className="flex flex-col items-center text-white">
            <Loader2 className="w-8 h-8 animate-spin mb-2 text-red-500" />
            <span className="text-sm font-medium">Generating AI Image...</span>
          </div>
        ) : (
          <button
            onClick={handleGenerate}
            className="flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-6 py-3 rounded-full font-medium transition-transform hover:scale-105 shadow-lg"
          >
            {hasKey ? <Sparkles size={18} /> : <Key size={18} />}
            {hasKey ? "Regenerate with AI" : "Generate AI Image"}
          </button>
        )}
      </div>
      
      {error && (
        <div className="absolute bottom-4 left-4 right-4 bg-red-900/80 text-white text-xs p-2 rounded border border-red-500 backdrop-blur-md">
          {error}
        </div>
      )}
    </div>
  );
}
